### ISSUE TITLE
Branch title

### ISSUE THREAD

**Issue by Knoficooki** [lloydbush/QualityGame#1]
its Jann if used

**Comment by lloydbush** [comment]
Hallo Jann.
Wie hast du das jetzt gemacht?

**Comment by lloydbush** [comment]
Ah, I see. Okay

**Comment by lorax42** [comment]
What's the problem/ issue?

**Comment by Knoficooki** [comment]
I would like a renaming of the branch

**Comment by lorax42** [comment]
Any suggestions?

**Comment by Knoficooki** [comment]
I mean, you named the branch "jan" after me right? Because I gave you the idea for the way of organising... so could you please write me not-completely-dead-name correctly?

**Comment by lorax42** [comment]
Of course, sorry about that. So just jann?

**Comment by Knoficooki** [comment]
Jup, or you can name it N0ffie... I think that would be best since it's my online name

**Comment by lorax42** [comment]
Will do
